### ISSUE TITLE
Incorrect ending for unfinished games

### ISSUE THREAD

**Issue by MarkZH** [jakeboone02/vscode-language-pgn#1]
Games that are adjourned are marked with a single asterisk *, not *-*.

Line 48 of syntaxes/pgn.tmLanguage should be

            <string>(1-0|0-1|1\/2-1\/2|\*)</string>

Line 77 should be

            <string>^\s*(1-0|0-1|1\/2-1\/2|\*)</string>

**Comment by jakeboone02** [comment]
Thanks, verified this [here](https://www.chessclub.com/help/PGN-spec) (section 8.1.1.7: The Result tag).

Would you mind submitting a PR to fix?

**Comment by jakeboone02** [comment]
Fix is [published](https://marketplace.visualstudio.com/items?itemName=jakeboone02.pgn).  Thanks!  :)
